spring:
  application:
    name: endpoint-insights-api
  datasource:
    url: jdbc:${DB_URI}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}


  jpa:
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true